### ISSUE TITLE
Artifact of Cognation string in English file does not match with the string in game.

### ISSUE THREAD

**Issue by SirPuppet** [TeamMoonstorm/MoonstormSharedUtils#10]
It's as it says. The in game string for the Artifact of Cognation is "SS2_ARTIFACT_COGNATION_NAME" and "SS2_ARTIFACT_COGNATION_DESCRIPTION", while in the English translation file, they are listed as "SS2_ARTIFACTCOGNATION_NAME" and "SS2_ARTIFACTCOGNATION_DESCRIPTION". As such, the translation string doesn't actually apply.

**Comment by TeamMoonstorm** [comment]
Closing issue due to this repository being now exclusively for MSU
