### ISSUE TITLE
SS2 - ISSUE_UNLOCKABLE_ACHIEVEMENT_NAME

### ISSUE THREAD

**Issue by gaforb** [TeamMoonstorm/MoonstormSharedUtils#13]
ISSUE_UNLOCKABLE_ACHIEVEMENT_DESCRIPTION
![image](https://user-images.githubusercontent.com/38703458/141780195-6b852f0f-23b9-4664-a546-488175b566b7.png)

**Comment by TeamMoonstorm** [comment]
Closing issue due to this repository being now exclusively for MSU
