### ISSUE TITLE
Game stuck on infinite loop

### ISSUE THREAD

**Issue by MajesticBard** [TeamMoonstorm/MoonstormSharedUtils#17]
When ever i try to launch RoR2 with moonstormSharedUtils enabled it gets stuck on 100%. is there any way i can fix it?

LOG:
[Message:   BepInEx] BepInEx 5.4.18.0 - Risk of Rain 2 (9/30/2021 4:16:16 PM)
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.18.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.Loader 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [FixPluginTypesSerialization 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.1.0.0]
[Info   :   BepInEx] 4 patcher plugins loaded
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Message:FixPluginTypesSerialization] Using the config cache
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   MonoMod] Collecting target assemblies from mods
[Info   :FixPluginTypesSerialization] Running under Unity v2018.4.16
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 45 plugins to load
[Info   :   BepInEx] Loading [Fem Acrid Edit 12G 1.0.1]
[Info   :   BepInEx] Loading [R2API 3.0.71]
[Info   :     R2API] Enabling R2API Submodule: ArtifactCodeAPI
[Info   :     R2API] Enabling R2API Submodule: BuffAPI
[Info   :     R2API] Enabling R2API Submodule: DamageAPI
[Info   :     R2API] Enabling R2API Submodule: DotAPI
[Info   :     R2API] Enabling R2API Submodule: ItemAPI
[Info   :     R2API] Enabling R2API Submodule: LanguageAPI
[Info   :     R2API] Enabling R2API Submodule: LoadoutAPI
[Info   :     R2API] Enabling R2API Submodule: PrefabAPI
[Info   :     R2API] Enabling R2API Submodule: RecalculateStatsAPI
[Info   :     R2API] Enabling R2API Submodule: ResourcesAPI
[Info   :     R2API] Enabling R2API Submodule: SoundAPI
[Info   :     R2API] Enabling R2API Submodule: SurvivorAPI
[Info   :     R2API] Enabling R2API Submodule: UnlockableAPI
[Info   :     R2API] Enabling R2API Submodule: CommandHelper
[Info   :     R2API] Enabling R2API Submodule: ILLine
[Info   :     R2API] Enabling R2API Submodule: NetworkingAPI
[Info   :   BepInEx] Loading [MiniRpcLib 1.1]
[Info   :MiniRpcLib] Initializing Logger
[Info   :MiniRpcLib] Initializing MiniRpc
[Info   :   Console] Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DMD<CollectHandlers>?72909824._RoR2_Networking_NetworkMessageHandlerAttribute::CollectHandlers () (at <0df3988a188242b1ae16fd51f05a8441>:IL_001F)
DMD<>?72909824.Trampoline<RoR2.Networking.NetworkMessageHandlerAttribute::CollectHandlers>?-1769989120 () (at <bbbdc93d4e444d87962583cb019c9eb6>:IL_0020)
MiniRpcLib.MiniRpc+<>c.<Initialize>b__11_2 (On.RoR2.Networking.NetworkMessageHandlerAttribute+orig_CollectHandlers orig) (at <5e7a149dc71c4445b3a6715caed3cf4a>:IL_0000)
DMD<>?72909824.Hook<RoR2.Networking.NetworkMessageHandlerAttribute::CollectHandlers>?1815965696 () (at <aa0acaf18c8d447eb38c46f918ff59f0>:IL_0014)
DMD<>?72909824.CallDelegate<CollectHandlers> (System.Object , System.Object[] ) (at <0993c45983a3416da7100a5e700ad0a5>:IL_0000)
R2API.Utils.Reflection.InvokeMethod[TReturn] (System.Type staticType, System.String methodName, System.Object[] methodParams) (at <1a583113fbfa4df0aa2a1c8cfc8b2b8f>:IL_0058)
R2API.Utils.Reflection.InvokeMethod[TReturn] (System.Type staticType, System.String methodName) (at <1a583113fbfa4df0aa2a1c8cfc8b2b8f>:IL_0000)
R2API.Utils.Reflection.InvokeMethod (System.Type staticType, System.String methodName) (at <1a583113fbfa4df0aa2a1c8cfc8b2b8f>:IL_0000)
MiniRpcLib.MiniRpc.Initialize (MiniRpcLib.RpcLayer.RpcLayer layer) (at <5e7a149dc71c4445b3a6715caed3cf4a>:IL_007C)
MiniRpcLib.MiniRpcPlugin..ctor () (at <5e7a149dc71c4445b3a6715caed3cf4a>:IL_0031)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

[Info   :   BepInEx] Loading [Riven 0.3.4]
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '<null>') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '<null>') is missing!
[Warning: Unity Log] RoR2.SurvivorDef must be instantiated using the ScriptableObject.CreateInstance method instead of new SurvivorDef.
[Info   :   BepInEx] Loading [Enigmatic Thunder 0.1.0]
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Util.ILLine :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Artifacts :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Bodies :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Buffs :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Effects :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Elites :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.GameEndings :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Languages :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.MusicTracks :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.NetworkPrefabs :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.NetworkSoundEvents :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Runs :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Scenes :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Sounds :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Loadouts :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Pickups :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Projectiles :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.Masters :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.SurfaceDefinitions :: Line: 101, Method GatherModules
[Info   :Enigmatic Thunder] EnigmaticThunder :: Enabling module: EnigmaticThunder.Modules.CommandHelper :: Line: 101, Method GatherModules
[Info   :   BepInEx] Loading [Acrid M1 Change 2.0.0]
[Info   :   BepInEx] Loading [AkaliMerc 1.0.1]
[Info   :   BepInEx] Loading [ArtificerExtended 3.1.5]
[Info   : Unity Log] ARTIFICEREXTENDED setup succeeded! Proceeding to allocate skill families!
[Info   : Unity Log] AE State Machines Set Up!
[Info   : Unity Log] ARTIFICEREXTENDED skill families reassigned! Proceeding to make Arti changes!
[Warning: Unity Log] RoR2.BuffDef must be instantiated using the ScriptableObject.CreateInstance method instead of new BuffDef.
[Info   :   BepInEx] Loading [This Loads An Extension For ArtificerExtended That Makes Some Strings Change If You Dont Have BalanceOverhaulRBO Installed 0.0.0]
[Info   :   BepInEx] Loading [SnoopDoggCommando 1.0.0]
[Info   :   BepInEx] Loading [Doommando 1.3.0]
[Info   :   BepInEx] Loading [InstantTeleporter 1.0.5]
[Info   :   BepInEx] Loading [Enforcer 3.2.5]
[Info   :   BepInEx] Loading [Ganondorf 1.0.3]
[Info   :   BepInEx] Loading [ShareSuite-R2 2.5.1]
[Info   :   BepInEx] Loading [Samus Huntress SKin 1.0.1]
[Info   :   BepInEx] Loading [Ninja 1.0.0]
[Error  : Unity Log] Trying to add a RendererInfo for a renderer that does not exist:
[Error  : Unity Log] mainRendererIndex out of range: not setting mainSkinnedMeshRenderer for mdlNinja
[Info   :   BepInEx] Loading [KingModUtilities 1.7.4]
[Info   :   BepInEx] Loading [GokuMod 2.11.0]
[Info   :   BepInEx] Loading [VegetaMod 1.3.0]
[Info   :   BepInEx] Loading [WarBannerBuff 4.0.0]
[Info   :   BepInEx] Loading [TF2SoldierMod 0.1.6]
[Error  : Unity Log] Failed to load effect: HenrySwordSwingEffect because it does not exist in the AssetBundle
[Error  : Unity Log] Failed to load effect: ImpactHenrySlash because it does not exist in the AssetBundle
[Error  : Unity Log] Failed to load material: NOTsoldier_red - Check to see that the name in your Unity project matches the one in this code
[Error  : Unity Log] Trying to add a RendererInfo for a renderer that does not exist: NOTsoldier_model
[Error  : Unity Log] mainRendererIndex out of range: not setting mainSkinnedMeshRenderer for TF2SollyBody
[Warning: Unity Log] The referenced script (DisplayModelController) on this Behaviour is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'SoldierTF2Display') is missing!
[Warning: Unity Log] The referenced script (DisplayModelController) on this Behaviour is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'SoldierTF2Display') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'SoldierTF2Display') is missing!
[Info   : Unity Log] Test1
[Info   : Unity Log] Test2
[Info   :   BepInEx] Loading [BiggerBazaar 1.12.13]
[Info   :   BepInEx] Loading [ScannerPlusOne 2.6.1]
[Info   :   BepInEx] Loading [ShrineOfDio 1.5.1]
[Info   :   BepInEx] Loading [FemMod 1.4.6]
[Info   :   BepInEx] Loading [Drop In Multiplayer 1.0.19]
[Info   :   BepInEx] Loading [Infinite Shrine of the Mountain 1.0.2]
[Info   :   BepInEx] Loading [Borpa 1.0.0]
[Info   :     Borpa] Hey
[Info   :     Trace] Initalizing character
[Info   :   BepInEx] Loading [Paladin 1.5.70]
[Info   :   BepInEx] Loading [FemSpyroHuntress 1.0.0]
[Info   :   BepInEx] Loading [ItemStats 2.2.1]
[Info   :   BepInEx] Loading [DeathMarkChange 1.1.4]
[Info   :   BepInEx] Loading [Moonstorm Shared Utils 0.7.0]
[Info   :   BepInEx] Loading [Lost in Transit 0.3.9]
[Info   :Moonstorm Shared Utils] Adding mod LostInTransit to the configurable field manager
[Info   :Moonstorm Shared Utils] Adding mod LostInTransit to the token modifier manager
[Info   :Lost in Transit] Initializing Buffs... :: Line: 20, Method Init
[Info   :     R2API] Custom Dot (Index: 7) that uses Buff : ThalliumPoison added
[Info   :Lost in Transit] Initializing Damage Types. :: Line: 15, Method Init
[Info   :Lost in Transit] Initializing Projectiles... :: Line: 20, Method Init
[Info   :Lost in Transit] Initializing Pickups... :: Line: 20, Method Init
[Info   :Lost in Transit] Initializing Elites... :: Line: 23, Method Init
[Info   :Lost in Transit] Volatile elites are enabled, setting up Volatile Bomb... :: Line: 107, Method BeginSetup
[Info   :Lost in Transit] Blighted elites are enabled, setting up systems... :: Line: 20, Method BeginSetup
[Info   :   BepInEx] Loading [MewtwoArtificer 1.0.1]
[Info   :   BepInEx] Loading [DekuMod 1.3.4]
[Info   :   BepInEx] Loading [The Names Doug Dimmadome Owner of the Dimmsdale Dimmadome 0.3.1]
[Info   :   BepInEx] Loading [KeepBanditSkull 1.1.0]
[Info   :   BepInEx] Loading [ModCommon 2.1.0]
[Info   :   BepInEx] Loading [HereticSelection 2.0.2]
[Info   :   BepInEx] Loading [HIFUHuntressTweaks 3.7.4]
[Info   :   BepInEx] Loading [HuntressAutoaimFix 1.0.6]
[Info   :   BepInEx] Loading [SAVAGECOMMANDO 6.6.6]
[Info   :   BepInEx] Loading [Pyke 0.1.1]
[Warning: Unity Log] Pyke: SoundBank name not provided; skipping
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DMD<CollectHandlers>?72909824._RoR2_Networking_NetworkMessageHandlerAttribute::CollectHandlers () (at <0df3988a188242b1ae16fd51f05a8441>:IL_001F)
DMD<>?72909824.Trampoline<RoR2.Networking.NetworkMessageHandlerAttribute::CollectHandlers>?-1769989120 () (at <bbbdc93d4e444d87962583cb019c9eb6>:IL_0020)
MiniRpcLib.MiniRpc+<>c.<Initialize>b__11_2 (On.RoR2.Networking.NetworkMessageHandlerAttribute+orig_CollectHandlers orig) (at <5e7a149dc71c4445b3a6715caed3cf4a>:IL_0000)
DMD<>?72909824.Hook<RoR2.Networking.NetworkMessageHandlerAttribute::CollectHandlers>?1815965696 () (at <aa0acaf18c8d447eb38c46f918ff59f0>:IL_0014)

[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
Setting breakpad minidump AppID = 632360
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198151823997 [API loaded no]
[Info   :   Console] Searching for compatible XInput library...
[Info   :   Console] Found Xinput1_4.dll.
[Info   : Unity Log] Initializing Mod System...
[Info   : Unity Log] Mod System initialized.
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   :     R2API] Custom sound banks loaded.
[Info   : Unity Log] Launch Parameters:
  arg[0]="D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2.exe"
  arg[1]="--doorstop-enable"
  arg[2]="true"
  arg[3]="--doorstop-target"
  arg[4]="C:\Users\user\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\ree\BepInEx\core\BepInEx.Preloader.dll"

[Info   : Unity Log] "exec" is not a recognized ConCommand or ConVar.
[Info   : Unity Log] "exec" is not a recognized ConCommand or ConVar.
[Info   :     R2API] Custom Buff: Warbanner(Buffed) added
[Info   :     R2API] Custom Survivor: RIVEN_NAME added
[Info   : Unity Log] LoadContentPacks() start
[Info   : Unity Log] Active scene changed from  to loadingbasic
[Info   : Unity Log] Loaded scene loadingbasic loadSceneMode=2
[Info   :     R2API] [NetworkCompatibility] Adding to the networkModList :
[Info   :     R2API] com.ArcsinJesse.Riven;0.3.4
[Info   :     R2API] com.bepis.r2api;3.0.71
[Info   :     R2API] com.Borbo.ArtificerExtended;3.1.5
[Info   :     R2API] com.EnforcerGang.Enforcer;3.2.5
[Info   :     R2API] com.Ethanol10.Ganondorf;1.0.3
[Info   :     R2API] com.HashAshin.MyNinjaMod;1.0.0
[Info   :     R2API] com.kking117.WarBannerBuff;4.0.0
[Info   :     R2API] com.Lemner.TF2SoldierMod;0.1.6
[Info   :     R2API] com.RainSL.Borpa;1.0.0
[Info   :     R2API] com.rob.Paladin;1.5.70
[Info   :     R2API] com.Skell.DeathMarkChange;1.1.4
[Info   :     R2API] com.swuff.LostInTransit;0.3.9
[Info   :     R2API] com.TeaL.DekuMod;1.3.4
[Info   :     R2API] com.TeamMoonstorm.MoonstormSharedUtils;0.7.0
[Info   :     R2API] dev.wildbook.libminirpc;1.1
[Info   :     R2API] HIFU.HIFUHuntressTweaks;3.7.4
[Info   :     R2API] HIFU.HuntressAutoaimFix;1.0.6
[Info   :     R2API] HIFU.SAVAGECOMMANDO;6.6.6
[Info   :     R2API] io.github.tntftw21.Pyke;0.1.1
[Message: ModCommon] Adding com.Windows10CE.HereticSelection to the network mod list...
[Info   : Unity Log] LoadContentPacks() end
[Info   : Unity Log] Game content load completed in 1962ms.
[Info   :Moonstorm Shared Utils] Initializing ConfigurableFieldManager
[Info   :Moonstorm Shared Utils] Setting up Interfaces
[Info   :Moonstorm Shared Utils] Subscribing to delegates related to damage types.
[Info   :Moonstorm Shared Utils] Subscribing to delegates related to Interactables
[Info   :Moonstorm Shared Utils] Initializing TokenModifierManager
[Info   : Unity Log] SystemInitializerAttribute infinite loop detected. currentMethod=Moonstorm.SceneModuleBaseHookInit
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.Stats.StatSheet.New () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0000)
RoR2.UserProfile..ctor () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_00CA)
RoR2.UserProfile+XmlUtility.FromXml (System.Xml.Linq.XDocument doc) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0000)
RoR2.UserProfile.LoadDefaultProfile () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_000A)
RoR2.UserProfile.LoadUserProfiles () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0014)
RoR2.RoR2Application+<OnLoad>d__60.MoveNext () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_01DB)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2cc17dca390941eeb4d7b2ff1f84696a>:IL_0027)

![image](https://user-images.githubusercontent.com/96651461/147383684-c3493a33-982b-4601-8ef7-b91036008b17.png)

**Comment by TeamMoonstorm** [comment]
Closing issue due to this repository being now exclusively for MSU
