### ISSUE TITLE
Teleporter in the wall

### ISSUE THREAD

**Issue by kellianoy** [TeamMoonstorm/MoonstormSharedUtils#2]
# Teleporter in the wall
## Issue

I was playing & chilling with StartStorm Nightly beta build when I encountered this quite laggy map known as Slate Mines. Being plundged into this beautiful stone paradise, I tried to find my way out to the teleporter.

Needless to say how shaken I was when I found out that I couldn't activate it because it's in the wall.
>mebeingdepressed.jpg

Couldn't get it to activate. It was stuck on the wall of the factory/machinery room.

`Good luck bois`

**Comment by TeamMoonstorm** [comment]
Closing issuedue to this repository being now exclusively for MSU
