### ISSUE TITLE
ItemIndex error spam when loading.

### ISSUE THREAD

**Issue by Moffein** [TeamMoonstorm/MoonstormSharedUtils#22]
When booting up the game with MSU, it spams "[Error  : Unity Log] ItemDef [ITEMNAME] has an item index of 'None'.  Attempting to fix..." for every single Vanilla item and equipment. Presumably because this is running before the ItemCatalog/EquipmentCatalog is initialized or something like that
[LogOutput.log](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/9187087/LogOutput.log)
.

**Comment by Nebby1999** [comment]
i reckon this should be already fixed by now, closing for now.

reopen if necesary
