### ISSUE TITLE
The Shader Elite Ramp Index isn't in the MS Elite Def Inspector

### ISSUE THREAD

**Issue by JaceDaDorito** [TeamMoonstorm/MoonstormSharedUtils#26]
A minor problem but I skipped over it a lot not realizing it was even a value I can set.

**Comment by Nebby1999** [comment]
funnily enough this should always be 0 when its being used for custom elite ramps, the issue is that i set it to -1 instead of 0

gonna fix it later

**Comment by Nebby1999** [comment]
This is technically fixed now due to R2API's EliteAPI (What MSU uses for the ramps) sets the index to 0.
