### ISSUE TITLE
Warning and Error log spam when booting up game

### ISSUE THREAD

**Issue by Pursec** [TeamMoonstorm/MoonstormSharedUtils#30]
Log is spammed with `Failed to assign ... Asset not found` warnings for almost every base game survivor/item and followed by Errors relating to Items, Buffs itemdefs returning 'null' aswell as other Exceptions such as ivalid keys or Null references

[LogOutput.log](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/10099599/LogOutput.log)

**Comment by Nebby1999** [comment]
Looking at the log you've sent there doesnt seem to be anything wrong with it? considering the fact that the only failed to assign bits are things from Starstorm2 that are disabled via the DisableContent attribute.

Are you sure you sent the correct log? going to close this for now.
