### ISSUE TITLE
Item Enabled / Disabled Events

### ISSUE THREAD

**Issue by swuff-star** [TeamMoonstorm/MoonstormSharedUtils#36]
Proposal for a flag to be added onto event cards that'd modify an event's eligibility after checking the inventories of each body on the player team for a specific item - ideally, could work both ways, with event cards that only are eligible to be selected if a player _does_ have an item, and event cards that are only eligible to be selected if a player _doesn't_ have an item.

**Comment by Nebby1999** [comment]
EventCard is subclassable, and IsAvailable is virtual, create a subclass of Eventcard and implement custom logic there.
