### ISSUE TITLE
Overhaul of Event Effect Prefabs to be Scene-Specific

### ISSUE THREAD

**Issue by swuff-star** [TeamMoonstorm/MoonstormSharedUtils#37]
Proposal that event effect prefabs be given scene-specific options, allowing for an event to take different appearances specific to each scene - would be extremely useful, as using a universal PP profile for an event causes some stages to look better or worse than others.

**Comment by Nebby1999** [comment]
Event effect prefabs are not somethinig handled by MSU instead, but by the mod youre making//working on
sorry
