### ISSUE TITLE
Dungus divides by 100 even though it specifies a decimal in config

### ISSUE THREAD

**Issue by gaforb** [TeamMoonstorm/MoonstormSharedUtils#4]
![image](https://user-images.githubusercontent.com/38703458/139560668-1f2c0042-4804-42c4-8063-f84a0dd269bf.png)

**Comment by gaforb** [comment]
Also this value gets added every half second so it's also multiplying the config value by two.

**Comment by TheTimeSweeper** [comment]
played latest update, and dungus now heals 100% health. it was overcorrected. 
To be clear, config now specifies 1 = 1% so it _should_ be dividing by 100 now

**Comment by TeamMoonstorm** [comment]
Closing issue due to this repository being now exclusively for MSU
