### ISSUE TITLE
Monsters / MonsterSpawnCards seem to be 1:1 rather than 1:m?

### ISSUE THREAD

**Issue by swuff-star** [TeamMoonstorm/MoonstormSharedUtils#46]
Vanilla uses multiple monster spawn cards per monster to control map specific loadouts which is primarily used for map specific skins - with MSU's current MSMDC implementation, it's only possible to associate one monster to one spawn card, thus making a similar implementation of a map-specific loadout like Vanilla's not possible with current setup.

**Comment by Nebby1999** [comment]
I'm unsure how to tackle this ATM, I might decide to create a custom version of Loadout and create an array of Loadout and Stage, that might work, but I'll keep this in mind for 1.7.0

**Comment by swuff-star** [comment]
Is it not possible to simply load multiple MSMDCs per body? Vanilla currently just uses multiple spawn cards - for example, a "Default" spawn card that's set to spawn on "normal" maps, a "Snowy" spawn card that is only set to be used for snowy maps, etc. It seems like it would be easier to simply allow multiple MSMDCs to be added to the pool per-body like Vanilla rather than refactoring how loadouts and stages are handled?

**Comment by Nebby1999** [comment]
I just pushed a commit that should adress this, now both MonsterBase and InteractableBase i've added a List version of the card, sadly i didnt make them abstract because that would be a breaking change with previous mods that depend on MSU.

Let me know if this works, i'll close this once you confirm

**Comment by swuff-star** [comment]
![image](https://github.com/TeamMoonstorm/MoonstormSharedUtils/assets/63352264/41247318-f30a-4728-b5c6-7f54d72bdde1)

Functional, gonna close. Thanks again!
