### ISSUE TITLE
Crashes and Mod Characters abilities overloading/not working later in runs.

### ISSUE THREAD

**Issue by ForeverDrivin** [TeamMoonstorm/MoonstormSharedUtils#48]
I'm posting this here because it seems the majority of my logfile mentions Moonstorm.

In playing with The Miner, Amp, Arsonist, and sometimes Paladin, it is possible to reach a point in a run where certain abilities overload/will cast too fast for anything to actually happen. This is not with something insane like 25 syringes either.

I have experienced:
- Paladin casting his special so fast that the aura just gets stuck in the cast phase with a small bubble.
- The Miner will swing his primary so fast it won't do damage and his special will randomly cast infinitely.
- Amp will not cast his special.
- Arsonist will not cast his special.

This output log contains the majority of errors I had from my last run where the Miner issues occurred, plus a crash at the end, but I did have to cut some middle stuff out due to the log being too big.

[LogOutput.log](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/12010598/LogOutput.log)

**Comment by u-lulu** [comment]
The log indicates that the version of Risk of Rain 2 running these mods is both pirated and outdated. Buy the game to fix your problem.

**Comment by Nebby1999** [comment]
We don't provide support for pirated versions.
