### ISSUE TITLE
Event-gated Monster and Interactable Cards

### ISSUE THREAD

**Issue by swuff-star** [TeamMoonstorm/MoonstormSharedUtils#50]
Cards that are only added to stages once specific criteria are met.

Long screenshot.
![Screenshot_20230716-150008](https://github.com/TeamMoonstorm/MoonstormSharedUtils/assets/63352264/268a3a5e-1f8b-4af9-97f1-b059113ad01b)

**Comment by Nebby1999** [comment]
This should already be implemented, but it's untested.

I'll close this for now, let me know if there's any issues
