### ISSUE TITLE
MINOR SPELLING ERROR!

### ISSUE THREAD

**Issue by klipsey** [TeamMoonstorm/MoonstormSharedUtils#56]
![image](https://github.com/user-attachments/assets/ff102397-ccea-429b-9a8e-fb769e4aab62)
![image](https://github.com/user-attachments/assets/d6a83692-4d45-4e8c-8451-cc0d8c938d04)

**Comment by gamrtiem** [comment]
this is the end of starstorm ,,,,

**Comment by Nebby1999** [comment]
Fixzed lmao
