### ISSUE TITLE
SS2 nightly crash error on dedicated server

### ISSUE THREAD

**Issue by 2biter** [TeamMoonstorm/MoonstormSharedUtils#7]
Only SS2 nightly build installed on steam RoR2 dedicated server

server log
[LogOutput.log](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/7488251/LogOutput.log)

unity crash
[Crash_2021-11-05_184353182.zip](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/7488266/Crash_2021-11-05_184353182.zip)

SS2 stable build working on dedicated server

**Comment by TeamMoonstorm** [comment]
Closing issue due to this repository being now exclusively for MSU
