### ISSUE TITLE
MSU 0.5.0 Crash on Start-up Log

### ISSUE THREAD

**Issue by Scrublord1337** [TeamMoonstorm/MoonstormSharedUtils#9]
New MSU update broke something. Here's the log. Only SS2 Nightly, LIT, and MSU + it's dependencies installed.
[MSU 0.5.0 Crash.txt](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/7499962/MSU.0.5.0.Crash.txt)

**Comment by kellianoy** [comment]
Same for me. Same messages & all.

**Comment by Nebby1999** [comment]
Duplicate of https://github.com/TeamMoonstorm/MoonstormSharedUtils/issues/8

For now, downgrade to MSU 0.4.1, this'll be fixed on version 0.5.1 of MSU.
